### ISSUE TITLE
`docs/references` is generated whenever `pytest` is run

### ISSUE THREAD

**Issue by alexdewar** [omicsNLP/Auto-CORPus#155]
Not the most important thing, but whenever I run `pytest`, it seems like the `docs/references` folder is regenerated and I'm not entirely sure how to fix it. From the pytest config it looks like the docs folder should be being ignored:

```toml
[tool.pytest.ini_options]
addopts = "-v -p no:warnings --cov=autocorpus --cov-report=html --doctest-modules --ignore=run_app.py --ignore=docs/"
```

I've also tried wrapping the contents of `gen_ref_nav.py` in an `if __name__ == "__main__"` but that didn't seem to fix things.

I must be misssing something. Any ideas @AdrianDAlessandro?
